name: pipeline
'on':
  push:
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, ubuntu-20.04 ]
        java: [ 11, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout reppository code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt-hotspot
          java-version: ${{ matrix.java }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build