name: pipeline
'on':
  push:
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-20.04 ]
        java: [ adopt@1.11, adopt@1.16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout reppository code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build